# spring.application.name=football-api
# # Port chay Web API
# server.port=8080

# # Cau hinh ket noi SQL Server
# spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=BookingFootball;encrypt=true;trustServerCertificate=true;
# spring.datasource.username=sa
# spring.datasource.password=Abc123456@

# # Cau hinh Hibernate (JPA) - Dan Java khong duoc tu y xoa bang SQL
# spring.jpa.hibernate.ddl-auto=none
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
# ===============================
# KẾT NỐI DATABASE SOMEE TRÊN MÂY
# ===============================
spring.datasource.url=jdbc:sqlserver://BookingFootballDB.mssql.somee.com;databaseName=BookingFootballDB;encrypt=true;trustServerCertificate=true;
spring.datasource.username=qnhatt_SQLLogin_1
spring.datasource.password=8jj5vv9d9r
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Cấu hình Hibernate (Giữ nguyên cấu trúc bảng đã tạo trên Somee)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true