spring.application.name=football-api
# Port chay Web API
server.port=8080

# Cau hinh ket noi SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=BookingFootball;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=Abc123456@

# Cau hinh Hibernate (JPA) - Dan Java khong duoc tu y xoa bang SQL
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect